"""added knot to pattern many-to-one

Revision ID: 0a91603cfc38
Revises: 
Create Date: 2021-12-18 15:17:20.575758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a91603cfc38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flasklogin-users')
    op.add_column('patterns', sa.Column('knot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patterns', 'knots', ['knot_id'], ['knot_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patterns', type_='foreignkey')
    op.drop_column('patterns', 'knot_id')
    op.create_table('flasklogin-users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"flasklogin-users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='flasklogin-users_pkey'),
    sa.UniqueConstraint('email', name='flasklogin-users_email_key')
    )
    # ### end Alembic commands ###
