"""cleaned up models

Revision ID: a72d88a80501
Revises: 
Create Date: 2021-12-19 17:29:41.522906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72d88a80501'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knots', 'total_cord')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knots', sa.Column('total_cord', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
