"""added creator_id to course

Revision ID: d1d614b267ed
Revises: 673d412e3d17
Create Date: 2021-11-25 10:32:27.219943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d614b267ed'
down_revision = '673d412e3d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'flasklogin-users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'creator_id')
    # ### end Alembic commands ###
